sudo: false
language: python
os:
  - linux
python:
  - "2.7"
  - "3.5"
matrix:
  include:
    - name: "C++"
      language: cpp
      install:
        - cd python
        - mkdir build
      script:
        - cd build
        - cmake ..
        - make
        - ctest
    - os: osx
      osx_image: xcode8.3
      python: "3.6-dev"
install:
  - pip install tox-travis
script:
  - cd python
  - tox
